version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: article_express
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: